---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: boshcpi/cpi-certification

inputs:
- name: environment
- name: bosh-stemcells-ci
- name: bosh-linux-stemcell-builder
- name: bosh-cli
- name: bosh-deployment
- name: stemcell

params:
  DEPLOY_ARGS: ""
  BAT_INFRASTRUCTURE: ""

outputs:
- name: director-state

run:
  path: bosh-stemcells-ci/pipelines/centos-7/master/bats/tasks/deploy-director.sh
