---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder

inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci
  - name: ubuntu-trusty-tarball

outputs:
  - name: bosh-linux-stemcell-builder-push

run:
  path: bosh-stemcells-ci/pipelines/ubuntu-trusty/3586.x/os-images/tasks/bump-os-image.sh
