jobs:
- name: repack-gcp
  plan:
  - in_parallel:
    - get: bosh-linux-stemcell-builder
    - get: bosh-agent
    - get: stemcell
      resource: gcp-stemcell
    - get: bosh-stemcells-ci
  - task: repack-stemcell
    privileged: true
    file: bosh-stemcells-ci/pipelines/repack-pipeline/repack-stemcell-gcp.yml
- name: repack-vsphere
  plan:
  - in_parallel:
    - get: bosh-linux-stemcell-builder
    - get: bosh-agent
    - get: stemcell
      resource: vsphere-stemcell
    - get: bosh-stemcells-ci
  - task: repack-stemcell
    privileged: true
    file: bosh-stemcells-ci/pipelines/repack-pipeline/repack-stemcell-vsphere.yml

resource_types:
- name: metalink-repository
  type: registry-image
  source:
    repository: dpb587/metalink-repository-resource

resources:
- name: bosh-linux-stemcell-builder
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-linux-stemcell-builder
    branch: master

- name: bosh-stemcells-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-stemcells-ci
    branch: master

- name: gcp-stemcell
  source:
    access_key_id: ((stemcell_aws_access_key))
    bucket: ((candidate_stemcell_bucket))
    regexp: google/bosh-stemcell-(.+)-google-kvm-ubuntu-xenial-go_agent.tgz
    secret_access_key: ((stemcell_aws_secret_key))
  type: s3

# - name: aws-stemcell
- name: bosh-agent
  type: metalink-repository
  source:
    uri: git+https://github.com/cloudfoundry/bosh-agent-index.git
    version: '*'

