---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ubuntu-chroot

inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci

run:
  path: bosh-stemcells-ci/pipelines/3586.x/tasks/test-unit.sh
