---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/os-image-stemcell-builder

inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci
  - name: version
  - name: stemcells-index

outputs:
  - name: stemcell
  - name: stemcells-index
    path: stemcells-index-output

run:
  path: bosh-stemcells-ci/tasks/build.sh

params:
  IAAS:            replace-me
  HYPERVISOR:      replace-me
  OS_NAME:         replace-me
  OS_VERSION:      replace-me
  STEMCELL_BUCKET: replace-me
