---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/main

inputs:
- name: bosh-linux-stemcell-builder
- name: bosh-stemcells-ci
- name: resolvconf-manager

outputs:
- name: bosh-linux-stemcell-builder

run:
  path: bosh-stemcells-ci/tasks/bump-resolvconf-manager.sh
