---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-publisher

inputs:
- name: bosh-stemcells-ci
- name: bosh-linux-stemcell-builder
- name: version
- name: stemcells-index

outputs:
- name: version-tag
- name: stemcells-index
  path: stemcells-index-output

run:
  path: bosh-stemcells-ci/tasks/publish.sh

params:
  AWS_ACCESS_KEY_ID:     required
  AWS_SECRET_ACCESS_KEY: required
  AWS_DEFAULT_REGION:    us-east-1
  FROM_BUCKET_NAME:      required
  TO_BUCKET_NAME:        required
  FROM_INDEX:            required
  TO_INDEX:              required
  COMMIT_PREFIX:         publish
  COPY_KEYS:             required
  OS_NAME:               required
  OS_VERSION:            required
