---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/main

inputs:
- name: bosh-linux-stemcell-builder
- name: bosh-stemcells-ci
- name: usn-source
- name: usn-log-in
  optional: true

outputs:
- name: usn-log-out

run:
  path: bosh-stemcells-ci/tasks/write-usn-message.sh
