---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/os-image-stemcell-builder

inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci
  - name: image-tarball

outputs:
  - name: bosh-linux-stemcell-builder-push

params:
  OS_NAME: ~
  OS_VERSION: ~

run:
  path: bosh-stemcells-ci/pipelines/ubuntu-xenial/170.x/os-images/tasks/bump-os-image.sh
