platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/main-base

params:
  BRANCH: ~
  PROJECT_ID: ~
  TOKEN: ~
  DESCRIPTION: ~

inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci

run:
  path: bosh-stemcells-ci/pipelines/ubuntu-xenial/97.x/tasks/create-story.sh
