---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/main-ubuntu-chroot

inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci

run:
  path: bosh-stemcells-ci/pipelines/ubuntu-xenial/170.x/tasks/test-unit.sh
