---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/compiled-release

inputs:
  - name: bosh-linux-stemcell-builder
  - name: bosh-stemcells-ci
  - name: environment
  - name: director-state

params:
  STEMCELL_NAME: null

outputs:
  - name: bats-config

run:
  path: bosh-stemcells-ci/pipelines/ubuntu-xenial/315.x/bats/iaas/vsphere/prepare-bats-config.sh
