---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/agent

inputs:
- name: bosh-linux-stemcell-builder
- name: bosh-stemcells-ci
- name: version

params: {}

run:
  path: bosh-stemcells-ci/pipelines/ubuntu-xenial/250.x/tasks/assert-version-aligns.sh
