---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/main

inputs:
- name: bosh-linux-stemcell-builder
- name: bosh-stemcells-ci
- name: bosh-agent

outputs:
- name: bosh-linux-stemcell-builder
  path: bosh-linux-stemcell-builder-out

run:
  path: bosh-stemcells-ci/pipelines/ubuntu-xenial/250.x/tasks/bump-bosh-agent.sh
