---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: boshcpi/cpi-certification

inputs:
- name: environment
- name: bosh-stemcells-ci
- name: bosh-linux-stemcell-builder
- name: bosh-cli
- name: bosh-deployment
- name: stemcell
- name: director-state
  optional: true

params:
  DEPLOY_ARGS: ""
  BAT_INFRASTRUCTURE: ""
  BOSH_CLIENT:
  BOSH_CLIENT_SECRET:
  BOSH_VSPHERE_VCENTER:
  BOSH_VSPHERE_VCENTER_CLUSTER:
  BOSH_VSPHERE_VCENTER_DATASTORE:
  BOSH_VSPHERE_VCENTER_DC:
  BOSH_VSPHERE_VCENTER_DISK_PATH:
  BOSH_VSPHERE_VCENTER_PASSWORD:
  BOSH_VSPHERE_VCENTER_RP:
  BOSH_VSPHERE_VCENTER_TEMPLATE_FOLDER:
  BOSH_VSPHERE_VCENTER_USER:
  BOSH_VSPHERE_VCENTER_VLAN:
  BOSH_VSPHERE_VCENTER_VM_FOLDER:
  BOSH_VSPHERE_VERSION:


outputs:
- name: director-state

run:
  path: bosh-stemcells-ci/tasks/bats/tasks/deploy-director.sh
